add option to randomize task order in grid environments

diff --git a/data/grid-job-body b/data/grid-job-body
--- a/data/grid-job-body
+++ b/data/grid-job-body
@@ -2,7 +2,12 @@ function format {
     printf "%05d" $1
 }
 
-RUN=$SGE_TASK_ID
+if [[ $SGE_TASK_ID < 1 || $SGE_TASK_ID > $NUM_TASKS ]]; then
+    echo "error: SGE_TASK_ID must be in range 1..$NUM_TASKS" 1>&2
+    exit 2
+fi
+
+RUN=${RUN_IDS[$(($SGE_TASK_ID-1))]}
 let "LOWER = ((RUN - 1) / 100) * 100 + 1"
 let "UPPER = (((RUN + 99) / 100) * 100)"
 DIR="runs-$(format $LOWER)-$(format $UPPER)/$(format $RUN)"
